<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
include('function.php');
define('TOKEN', '5058820674:AAEP9gSTbJsdAgo54NQEDzBxqXczYkg5oDs');
define('ADMINS', [173218220, 526456686]);
define('MAIN_KOF', 1.05);
define('COMMISSION', 90);
define('IBLOCK_ID_HORDE', 6);
define('IBLOCK_ID_ALLIANCE', 7);
define('IBLOCK_ID_SHIELT', 8);
define('IBLOCK_ID_HEAL', 9);
define('IBLOCK_ID_DD', 10);
define('IBLOCK_ID_USER', 5);
define('IBLOCK_ID_PLAYERS', 11);
define('IBLOCK_ID_PLAYERS_RATES', 12);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);
// define('IBLOCK_ID_', value);